# web_builder_agent.py — pip install requests gitpython
import os
import subprocess
import requests

# This agent: generates website code using Claude API, deploys to GitHub Pages FREE

GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN')  # Free at github.com/settings/tokens
GITHUB_USER = os.environ.get('GITHUB_USER', 'YOUR_USERNAME')

def create_github_repo(repo_name):
    if not GITHUB_TOKEN:
        print("GITHUB_TOKEN not set. Cannot create repo.")
        return None
    # Create repo via GitHub API — FREE
    r = requests.post(
        'https://api.github.com/user/repos',
        headers={'Authorization': f'token {GITHUB_TOKEN}'},
        json={'name': repo_name, 'auto_init': True, 'private': False})
    res_json = r.json()
    if 'html_url' not in res_json:
        print(f"Error creating repository: {res_json}")
        return None
    return res_json['html_url']

def deploy_to_github_pages(repo_name, html_content, js_content=''):
    if not GITHUB_TOKEN or GITHUB_USER == 'YOUR_USERNAME':
        print("GITHUB_TOKEN or GITHUB_USER is not configured. Cannot deploy.")
        return None
    # Push files to GitHub — auto deploys to Pages
    import base64
    files = {'index.html': html_content, 'app.js': js_content}
    for fname, content in files.items():
        encoded = base64.b64encode(content.encode()).decode()
        requests.put(
            f'https://api.github.com/repos/{GITHUB_USER}/{repo_name}/contents/{fname}',
            headers={'Authorization': f'token {GITHUB_TOKEN}'},
            json={'message': f'Deploy {fname}', 'content': encoded})
    # Enable GitHub Pages
    requests.post(
        f'https://api.github.com/repos/{GITHUB_USER}/{repo_name}/pages',
        headers={'Authorization': f'token {GITHUB_TOKEN}'},
        json={'source': {'branch': 'main', 'path': '/'}})
    site_url = f"https://{GITHUB_USER}.github.io/{repo_name}"
    print(f"Live at: {site_url}")
    return site_url

if __name__ == "__main__":
    print("Running Web Builder agent...")
    SAMPLE_HTML = """<!DOCTYPE html><html><head>
<title>Top AI Tools 2026</title>
<meta name="description" content="Best free AI tools">
</head><body style="font-family:sans-serif;max-width:900px;margin:0 auto">
<h1>Top 10 Free AI Tools</h1>
<p>Generated by Zero Cost AI Agent Empire dashboard.</p>
</body></html>"""

    if GITHUB_TOKEN and GITHUB_USER != 'YOUR_USERNAME':
        repo = create_github_repo('ai-tools-2026')
        if repo:
            site = deploy_to_github_pages('ai-tools-2026', SAMPLE_HTML)
            print(f"Website live: {site}")
    else:
        print("GITHUB_TOKEN or GITHUB_USER not set. Writing local file instead.")
        with open("sample_website.html", "w") as f:
            f.write(SAMPLE_HTML)
        print("Wrote output to sample_website.html")